export const ADD = 'ADD'
export const SUB = 'SUB'
export const SET_COUNTER = 'SET_COUNTER'

export const FETCH_INITIAL_PROJECT_SUCCESS = 'FETCH_INITIAL_PROJECT_SUCCESS'
export const FETCH_INITIAL_PROJECT_START = 'FETCH_INITIAL_PROJECT_START'

export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS'


export const UPDATE_PROJECT_PROPERTY = 'UPDATE_PROJECT_PROPERTY'
export const UPDATE_PROJECT_PROPERTY_START = 'UPDATE_PROJECT_PROPERTY_START'
export const UPDATE_PROJECT_PROPERTY_PATCH = 'UPDATE_PROJECT_PROPERTY_PATCH'
export const UPDATE_PROJECT_PROPERTY_RELOADER = 'UPDATE_PROJECT_PROPERTY_RELOADER'
export const UPDATE_PROJECT_PROPERTY_SUCCESS = 'UPDATE_PROJECT_PROPERTY_SUCCESS'

export const UPDATE_PROJECT_TODOS_INIT = 'UPDATE_PROJECT_TODOS_INIT'
export const UPDATE_PROJECT_TODOS_START = 'UPDATE_PROJECT_TODOS_START'
export const UPDATE_PROJECT_TODOS_PATCH = 'UPDATE_PROJECT_TODOS_PATCH'



export const INIT_CREATE_PROJECT = 'INIT_CREATE_PROJECT'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'

