export const ADD = 'ADD'
export const SUB = 'SUB'
export const SET_COUNTER = 'SET_COUNTER'

export const FETCH_INITIAL_PROJECT_SUCCESS = 'FETCH_INITIAL_PROJECT_SUCCESS'
export const FETCH_INITIAL_PROJECT_START = 'FETCH_INITIAL_PROJECT_START'

export const FETCH_PROJECT = 'FETCH_PROJECT'
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS'


export const INIT_CREATE_PROJECT = 'INIT_CREATE_PROJECT'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'